version: '3'

services:
  web:
    container_name: ${APP_NAME}_web
    build:
      context: ./docker/web
    ports:
      - 80:80
    volumes:
      - ./:/var/www/app
    networks:
        - app-network
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=yourdb
    networks:
        - app-network
  phpmyadmin:
          container_name: ${APP_NAME}_phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - "7000:80"
          links:
            - db:db
          environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
          networks:
            - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge




















    