# AWS automated deployment -
name: Deploy
on:
    push:
    branches: [ master ]

jobs:
    copy-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: copy files
        uses: appleboy/scp-action@v0.1.1
        with:
        host: @php
        echo '${{ secrets.HOST }}'
    @endphp

        username: @php
            echo '${{ secrets.USERNAME }}'
        @endphp

        key: @php
            echo '${{ secrets.KEY }}'
        @endphp

        port: @php
            echo '${{ secrets.PORT }}'
        @endphp

        overwrite: true
        source: "./*"
        target: "/var/www/growbeans"
