# AWS automated deployment --
  on:
    push:
      branches:
        - master
  
  name: DEV Build to Amazon EC2
  
  jobs:
    build:
      name: copy files
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
  
      - name: copy files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          overwrite: true
          source: "./*"
          target: "/var/www/growbeans"        